# Generated by Django 5.0.6 on 2024-05-25 04:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='laboratorystaff',
            old_name='staff_address',
            new_name='address',
        ),
        migrations.RenameField(
            model_name='laboratorystaff',
            old_name='staff_phone',
            new_name='phone',
        ),
        migrations.RenameField(
            model_name='laboratorystaff',
            old_name='staff_role',
            new_name='role',
        ),
        migrations.RenameField(
            model_name='laboratorystaff',
            old_name='staff_status',
            new_name='status',
        ),
    ]
