# Generated by Django 5.0.6 on 2024-05-26 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0003_alter_laboratorystaff_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='laboratorystaff',
            name='role',
            field=models.CharField(choices=[('STAFF', 'Laboratory Staff'), ('OWNER', 'Laboratory OWNER')], default='STAFF', max_length=50),
        ),
    ]
