# Generated by Django 5.0.6 on 2024-05-27 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0005_patient'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='nic',
            field=models.CharField(max_length=12, null=True),
        ),
    ]
