# Generated by Django 5.0.6 on 2024-05-28 03:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0006_alter_patient_nic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='title',
            field=models.CharField(choices=[('Mr.', 'Mr.'), ('Mrs.', 'Mrs.'), ('Miss.', 'Miss.'), ('Dr.', 'Dr.'), ('Ms.', 'Ms.'), ('Master.', 'Master.')], max_length=10),
        ),
    ]
