# Generated by Django 5.0.6 on 2024-05-27 03:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0005_patient'),
        ('reportgenapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reportformats',
            old_name='specimentype',
            new_name='specimen_type',
        ),
        migrations.AddField(
            model_name='reportgen',
            name='patient',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='authapp.patient'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reportgen',
            name='report_format',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='reportgenapp.reportformats'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reportgen',
            name='status',
            field=models.CharField(choices=[('SAMPLE_PENDING', 'Sample Pending'), ('PENDING', 'Pending'), ('GENERATED', 'Generated'), ('DELIVERED', 'Delivered')], default='SAMPLE_PENDING', max_length=20),
        ),
        migrations.AddField(
            model_name='reportgen',
            name='values',
            field=models.JSONField(default=1),
            preserve_default=False,
        ),
    ]
