# Generated by Django 5.0.6 on 2024-05-27 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reportgenapp', '0003_reportgen_created_at_reportgen_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reportgen',
            name='values',
            field=models.JSONField(null=True),
        ),
    ]
