# Generated by Django 5.0.6 on 2024-05-28 04:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0007_alter_patient_title'),
        ('reportgenapp', '0004_alter_reportgen_values'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ReportGen',
            new_name='PatientReportsRequest',
        ),
    ]
