# Generated by Django 5.0.6 on 2024-05-28 04:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reportgenapp', '0005_rename_reportgen_patientreportsrequest'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ReportFormats',
            new_name='ReportFormat',
        ),
    ]
