# Generated by Django 5.0.6 on 2024-05-28 04:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0007_alter_patient_title'),
        ('reportgenapp', '0006_rename_reportformats_reportformat'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportRequest',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authapp.patient')),
            ],
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('values', models.JSONField()),
                ('status', models.CharField(choices=[('SAMPLE_PENDING', 'Sample Pending'), ('PENDING', 'Pending'), ('GENERATED', 'Generated'), ('DELIVERED', 'Delivered')], default='SAMPLE_PENDING', max_length=20)),
                ('has_paid', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('report_format', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reportgenapp.reportformat')),
                ('patient_report_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reportgenapp.reportrequest')),
            ],
        ),
        migrations.DeleteModel(
            name='PatientReportsRequest',
        ),
    ]
