# Generated by Django 5.0.6 on 2024-05-28 04:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reportgenapp', '0007_reportrequest_report_delete_patientreportsrequest'),
    ]

    operations = [
        migrations.RenameField(
            model_name='report',
            old_name='patient_report_request',
            new_name='report_request',
        ),
    ]
