# Generated by Django 5.0.6 on 2024-05-28 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reportgenapp', '0008_rename_patient_report_request_report_report_request'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='values',
            field=models.JSONField(null=True),
        ),
    ]
