# Generated by Django 5.0.6 on 2024-05-29 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reportgenapp', '0009_alter_report_values'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='referred_by',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
