# Generated by Django 5.0.6 on 2024-05-29 05:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0007_alter_patient_title'),
        ('reportgenapp', '0010_report_referred_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reportrequest',
            name='patient',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='authapp.patient'),
        ),
    ]
