# Generated by Django 5.0.6 on 2024-06-02 00:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reportgenapp', '0012_reportrequest_age_reportrequest_gender_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
    ]
