# Generated by Django 5.0.6 on 2024-06-02 03:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reportgenapp', '0013_report_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='reportformat',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
    ]
