# Generated by Django 5.0.6 on 2024-06-02 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reportgenapp', '0016_reportformat_generation_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='delivery_date',
            field=models.DateTimeField(null=True),
        ),
    ]
