# Generated by Django 5.0.6 on 2024-06-03 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reportgenapp', '0017_report_delivery_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('GENERATED', 'Generated')], default='PENDING', max_length=20),
        ),
    ]
