# Generated by Django 5.0.6 on 2024-06-04 02:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reportgenapp', '0018_alter_report_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='sample_id',
            field=models.CharField(max_length=8, null=True),
        ),
    ]
